CREATE TABLE IF NOT EXISTS Players (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Nickname TEXT NOT NULL UNIQUE,
    BattleTag TEXT NOT NULL UNIQUE,
    Toon TEXT NOT NULL UNIQUE,
    CreatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_players_battletag ON Players(BattleTag);
CREATE INDEX IF NOT EXISTS idx_players_toon ON Players(Toon);
CREATE INDEX IF NOT EXISTS idx_players_nickname ON Players(Nickname);
